# Generated by Django 3.2.15 on 2022-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='projectPermit',
        ),
        migrations.AddField(
            model_name='role',
            name='projectPermit',
            field=models.ManyToManyField(to='project.ProjectPermit'),
        ),
    ]
